#!/bin/sh
uci del network.globals.ula_prefix
uci set network.globals.packet_steering='1'
uci set network.wan6.reqaddress='force'
uci set network.wan6.reqprefix='64'
uci set network.wan6.extendprefix='1'
uci set network.wan6.norelease='1'
uci set network.wan6.ip6assign='64'
uci commit network

uci del dhcp.lan.ra_slaac
uci del dhcp.lan.ra_flags
uci add_list dhcp.lan.ra_flags='other-config'
uci set dhcp.lan.ra='hybrid'
uci set dhcp.lan.dhcpv6='hybrid'
uci set dhcp.lan.ndp='hybrid'

uci add dhcp host # =cfg06fe63
uci set dhcp.@host[-1].name='homelab'
uci add_list dhcp.@host[-1].mac='c2:4f:ab:0a:95:4f'
uci set dhcp.@host[-1].ip='192.168.31.159'
uci set dhcp.@host[-1].leasetime='12h'
uci commit dhcp

uci add firewall redirect # =cfg123837
uci set firewall.@redirect[-1].dest='lan'
uci set firewall.@redirect[-1].target='DNAT'
uci set firewall.@redirect[-1].name='Sunshine'
uci set firewall.@redirect[-1].src='wan'
uci set firewall.@redirect[-1].src_dport='47984-48010'
uci set firewall.@redirect[-1].dest_ip='192.168.31.159'
uci set firewall.@redirect[-1].dest_port='47984-48010'
uci commit firewall

uci set socat.d7cacd358c3d430b8f005e5fc8413466=config
uci set socat.d7cacd358c3d430b8f005e5fc8413466.enable='0'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.firewall_accept='1'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.enable='1'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.remarks='TLS'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.protocol='port_forwards'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.family='4'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.proto='tcp'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.listen_port='8443'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.reuseaddr='1'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.dest_proto='tcp4'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.dest_ip='192.168.31.159'
uci set socat.d7cacd358c3d430b8f005e5fc8413466.dest_port='8443'
uci commit socat

/etc/init.d/network restart
/etc/init.d/firewall restart
/etc/init.d/socat restart

uci add fstab mount # =cfg064d78
uci set fstab.@mount[-1].enabled='1'
uci set fstab.@mount[-1].label='extroot'
uci set fstab.@mount[-1].target='/overlay'
uci set fstab.@mount[-1].fstype='btrfs'
uci commit fstab

reboot
